name: check broken urls

on:
  push

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://www.example.com/test123
          cmd_params: "--one-page-only --max-connections=3 --color=always"  # Check just one page
