name: check broken urls

on:
  push

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    
    steps:
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: report, automated issue
