name: linkchecker pipeline
on:
  push

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install linkchecker
          pip install polib
          pip install git+https://github.com/linkchecker/linkchecker.git
     
      - name: Create annotation for build error
        id: vars
        run: |
          linkchecker --check-extern -t 50 https://500apps.com > result_file.txt
          cat result_file.txt
      
      - name: Set AWS credentials
        uses: jakejarvis/s3-sync-action@master 
        with: 
          args: --acl public-read --follow-symlinks --exclude '.git/*'
        env:
          FILE: "/home/runner/work/testing/testing/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'ap-south-1'
#           SOURCE_DIR: 'public'      # optional: defaults to entire repository











































