name: Scrapping for owfis

on: 
  push:
  workflow_dispatch:

jobs:
  publish:
    name: Scrapping
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Scrapping data
        run: |
          mkdir -p scrape/xml_files
