name: Scrapping for owfis

on: 
  workflow_dispatch:

jobs:
  publish:
    name: Scrapping
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Scrapping data
        run: |
          mkdir scrape/xml_files
